### ISSUE TITLE
Gps problema

### ISSUE THREAD

**Issue by escarlos** [dadapunk/AmucanApp#3]
El gps no actualiza a la ubicacion en la que se encuentra actualmente el usuario

**Comment by dadapunk** [comment]
Probé en un dos locaciones distintas y funciona.

**Comment by escarlos** [comment]
lo arreglaste o es algo del duoc?

**Comment by dadapunk** [comment]
Al parecer es algo de esa locación en particular, pero hay que hacer mas pruebas para estar seguro.
Hice un nuevo apk con algunos cambios, necesito que la prueben.

**Comment by dadapunk** [comment]
it works
